pod 'ReactiveCocoa', '2.5'
pod 'ReactiveCocoaLayout', '~> 0.4'
pod 'Mantle', '~> 2.0'
pod 'ReactiveViewModel', '~> 0.3'
pod 'Masonry', '~> 0.6.1'
pod 'AFNetworking', '~> 2.5.3'
pod 'JSONKit', '~> 1.5pre'
pod 'SDWebImage', '~> 3.7.2'
pod 'MMProgressHUD', '~> 0.3.1'